# Generated by Django 3.0.3 on 2020-02-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Known',
        ),
    ]
