# Generated by Django 3.0.3 on 2020-02-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_auto_20200226_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unknown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='missing_faces/Known')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
