# Generated by Django 3.0.3 on 2020-02-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_unknown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='unknown',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='unknown',
            name='image',
            field=models.ImageField(blank=True, upload_to='missing_faces/Unknown'),
        ),
    ]
