# Generated by Django 3.0.3 on 2020-03-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_auto_20200226_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file_type',
            field=models.CharField(choices=[('image', 'image')], default=0, max_length=256),
            preserve_default=False,
        ),
    ]
