# Generated by Django 3.0.3 on 2020-03-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0006_question_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='Known'),
        ),
        migrations.AlterField(
            model_name='unknown',
            name='image',
            field=models.ImageField(blank=True, upload_to='Unknown'),
        ),
    ]
