# Generated by Django 3.0.3 on 2020-03-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0008_auto_20200303_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='Known'),
        ),
    ]
