# Generated by Django 3.0.3 on 2020-03-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0009_auto_20200303_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
