# Generated by Django 3.0.3 on 2020-03-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0010_auto_20200303_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
