# Generated by Django 3.0.3 on 2020-03-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0011_question_image_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unknown',
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(),
        ),
    ]
