# Generated by Django 3.0.3 on 2020-03-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0013_auto_20200319_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
